### ISSUE TITLE
Updated gizmos

### ISSUE THREAD

**Issue by Njordy** [CreativeLyons/NukeSurvivalToolkit_publicRelease#13]
DasGrain got an important update: 

> v1.8
> - updated UI and many of the tooltips (let me know what you think!)
> - fixed a fundamental bug in the per channel range script
> - added a metadata knob to choose between plate and comp
> - added a threshold, so that a sample has to contain at least 10 pixels to be used
> - deleted the colorspace choice in the two colorspace knobs so on first load it will be set to whatever is the default space in your config rather than potentially error.
> - updated Python scripts to be Nuke 13 compatible
> - fixed and improved many minor things

**Comment by CreativeLyons** [comment]
updated DasGrain to 1.8
