### ISSUE TITLE
deadline brakes experssions

### ISSUE THREAD

**Issue by ChromaKiki** [CreativeLyons/NukeSurvivalToolkit_publicRelease#21]
I noticed the repeated error on many gizmos where parent or parent name is broken, mostly expression linking gets broken.
Nothing is named ...very common, and when you look inside gizmo (converting to group) all is there and named properly.
Obviously, in GUI all works as expected, without errors. Things start popping when deadline goes through it. Even Das Grain has the same issue.

**Comment by Kaiz3rTool** [comment]
APnodes are creating this problem

**Comment by CreativeLyons** [comment]
marking this as closed, need more detail.  exact node. exact bug. if you capture an error in a specific node, let me know and I can sort it out. thank you.
