### ISSUE TITLE
Is it safe to use non-release version

### ISSUE THREAD

**Issue by Njordy** [CreativeLyons/NukeSurvivalToolkit_publicRelease#24]
Hi.
There haven't been a new official release since middle of last year. 
But I do see what updates to the files are happening. 
Is this (semi-) safe to clone the repo and just use it as it is?

**Comment by CreativeLyons** [comment]
yes, it should be completely safe.  Bit hard to keep the documentation up to date, and I need that for the official releases.  I was also trying to migrate the documentation to mkdocs and readTheDocs for ease of use / editing, but had some roadblocks.  Let me know if it's ever completely broken though, and I'll have a look at specific areas and update.
