### ISSUE TITLE
Cell noise Kernel Problem

### ISSUE THREAD

**Issue by Iandres9** [CreativeLyons/NukeSurvivalToolkit_publicRelease#25]
In Nuke 13.2v2 adding a cellnoise node will drop an this *error compiling kernel 
Will happen both in CPU and GPU.

**Comment by jeangjenq** [comment]
Was testing this with coworkers, seems to be a Nuke13.2 bug.

https://support.foundry.com/hc/en-us/articles/6076518649106-ID-511559-Fetching-a-sample-value-using-square-brackets-BlinkScript-fails-to-compile-on-the-GPU

Cell Noise works on 13.1.
