### ISSUE TITLE
CellNoise

### ISSUE THREAD

**Issue by martinkarlssonvfx** [CreativeLyons/NukeSurvivalToolkit_publicRelease#3]
Hi, thanks for a fantastic tool. 

I'm getting an issue with Cellnoise.

Cellnoise,WorleyNoise: Error compiling kernel for GPU.

Cheers

**Comment by CreativeLyons** [comment]
Check if the version of nuke you are using is compatible with blink scripts.  Also, sometimes blink scripts don't work well with some GPU's and you'll need to uncheck the use GPU checkbox on the blink node.
