### ISSUE TITLE
python line not working

### ISSUE THREAD

**Issue by IM-001** [CreativeLyons/NukeSurvivalToolkit_publicRelease#4]
Fantastic tool for people like me who have to search by themselves for the good gizmos out there : )

 There is one slight error in your latest build though I think.  The line 18 of the file "NukeSurvivalToolkit\nuke-vector-matrix\menu.py" (prefixNST = "NST_") should not be commented out, it throws an error on my side.  All good if I remove the #.  Many thanks!

**Comment by CreativeLyons** [comment]
Should be solved with new update.
