### ISSUE TITLE
"dir" keyword used in init.py

### ISSUE THREAD

**Issue by simonbjork** [CreativeLyons/NukeSurvivalToolkit_publicRelease#8]
In NukeSurvivalToolkit init.py the variable "dir" is used. This is overrides the built-in keyword in python and breaks the functionality in scripts that use it (and in the script editor, just test `dir(nuke)`).

It should be fixed easily by using another variable name that dir.

**Comment by CreativeLyons** [comment]
Should be solved with new update, thank you.
